Add wallet_address to scopes
pi-apps/pi-platform-docs pull request #307
Opened 2023-01-20 19:08 UTC by CryptoGing

Added wallet_address to the available scopes, and made a number of formatting changes to make it more clear what scopes are needed for what methods.

2023-01-31 19:16 UTC, linnielowe06 approved these changes

2023-02-05 18:10 UTC, Khaledluck commented
why?

2023-02-19 09:27 UTC, zainshafqat approved these changes

2023-02-19 09:33 UTC, zainshafqat approved these changes

2023-03-31 11:39 UTC, Akinte2 commented
Hi I'm longtime pchain holder who wants to make a node, I find it very easy to setup a node with Ankro so here I am. Akinte Toluwalase

2023-04-02 20:42 UTC, fakhroshumailasabri786 approved these changes
My payment what

2023-04-24 08:58 UTC, ZxSix666 approved these changes

2023-05-15 00:51 UTC, crazybow369981 commented
Hhh

2023-05-20 04:04 UTC, SaNaMoe commented
GA6ITZTQRWJJF3SWLCVXZVSJCDTPROATPK7FKHA2VM55PCBUDY3X2PYE

2023-05-20 04:11 UTC, SaNaMoe reviewed
GBCT2ZKP3GAITRA4XQH5C4ICCJWKF3GGPXU2Q7JFN7T3LXCN4C4ELKNV

2023-05-30 08:18 UTC, wasi4440 commented
GDFVAMD4O27736SX6UHRAXQIMO4TH3G4HXWIP6RBVITURG7GQVSJLKXB

2023-05-30 09:25 UTC, SaNaMoe reviewed
My wallet address -(GBCT2ZKP3GAITRA4XQH5C4ICCJWKF3GGPXU2Q7JFN7T3LXCN4C4ELKNV)

2023-05-30 09:59 UTC, SaNaMoe reviewed
My wallet address -(GBCT2ZKP3GAITRA4XQH5C4ICCJWKF3GGPXU2Q7JFN7T3LXCN4C4ELKNV)

2023-06-06 23:56 UTC, wasi4440 commented
GBFTP3KV6NXMECJ66XKT6FDWCXSLPKO4EY4FG2GOKSGY6NPHBWQQVUYB

2023-06-06 23:59 UTC, wasi4440 commented on SDK_reference.md
> +| `wallet_address` | Gives the app access to the users public wallet address | `createPayment` - App to User Payments|
GBFTP3KV6NXMECJ66XKT6FDWCXSLPKO4EY4FG2GOKSGY6NPHBWQQVUYB

2023-06-06 23:59 UTC, wasi4440 commented on SDK_reference.md
> +Available scopes: `username`, `payments`, `wallet_address`.
GBFTP3KV6NXMECJ66XKT6FDWCXSLPKO4EY4FG2GOKSGY6NPHBWQQVUYB

2023-06-07 22:17 UTC, SaNaMoe commented on SDK_reference.md
> -Available scopes: `username`, `payments`.
User name - SaNaMoe

2023-06-07 22:19 UTC, SaNaMoe commented on SDK_reference.md
> +Available scopes: `username`, `payments`, `wallet_address`.
My wallet address -GBCT2ZKP3GAITRA4XQH5C4ICCJWKF3GGPXU2Q7JFN7T3LXCN4C4ELKNV

2023-06-09 07:37 UTC, samerbashour commented
GDWWWJ25VSVI2HOLJXHH4XRU6EEJDHZ74KHZ2JF3QAIJWSM6DH5GSSZ5

2023-06-09 07:38 UTC, samerbashour commented
GDWWWJ25VSVI2HOLJXHH4XRU6EEJDHZ74KHZ2JF3QAIJWSM6DH5GSSZ5

2023-06-10 02:28 UTC, samerbashour reviewed
GDWWWJ25VSVI2HOLJXHH4XRU6EEJDHZ74KHZ2JF3QAIJWSM6DH5GSSZ5

2023-06-10 03:22 UTC, SaNaMoe commented
> GDWWWJ25VSVI2HOLJXHH4XRU6EEJDHZ74KHZ2JF3QAIJWSM6DH5GSSZ5

GBCT2ZKP3GAITRA4XQH5C4ICCJWKF3GGPXU2Q7JFN7T3LXCN4C4ELKNV

2023-06-30 23:16 UTC, Fares712 commented
GDMXMUD7FCMN4Y6QZ4M3WR4V2IBH4TJZ5W55EQ4HLNXRDUFYNCIAZ7SO

2023-07-01 07:40 UTC, SaNaMoe commented
GBCT2ZKP3GAITRA4XQH5C4ICCJWKF3GGPXU2Q7JFN7T3LXCN4C4ELKNV

On Sat, 1 Jul 2023, 2:16 am Fares712, ***@***.***> wrote:

> GDMXMUD7FCMN4Y6QZ4M3WR4V2IBH4TJZ5W55EQ4HLNXRDUFYNCIAZ7SO
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pi-apps/pi-platform-docs/pull/307#issuecomment-1615268266>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A76XZILLC5ELDOCAUXQ725DXN5M5XANCNFSM6AAAAAAUB3INME>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-07-02 13:32 UTC, Okorie150 commented
GABLZ2C3TINCYOWI7KCOCCJZX7EOJQ6T2BNI4TSRT3C6Q3HPRI64VTZG

2023-07-04 02:34 UTC, ahmeed38 commented on SDK_reference.md
> +Available scopes: `username`, `payments`, `wallet_address`.
!

2023-07-04 02:34 UTC, ahmeed38 commented on SDK_reference.md
> +| `wallet_address` | Gives the app access to the users public wallet address | `createPayment` - App to User Payments|
ok

2023-07-06 05:49 UTC, Stancy1234567 commented on SDK_reference.md
> +Available scopes: `username`, `payments`, `wallet_address`.
GACJXMWK23KTJJISEYHUF47OU5OFKFHVJV2KZZRTQJRNCOYU7MDJMWPP

2023-07-09 23:03 UTC, Lirofi approved these changes

2023-07-12 22:51 UTC, wasi4440 approved these changes

2023-07-12 22:52 UTC, wasi4440 reviewed
SDK_reference.md

2023-07-13 04:44 UTC, Okorie150 commented
GABLZ2C3TINCYOWI7KCOCCJZX7EOJQ6T2BNI4TSRT3C6Q3HPRI64VTZG

2023-07-13 07:22 UTC, Lirofi commented
GB3XZRSCP7AGDQ6EKOCM7FANLYF2EYMHMQAB5PW42JI6X7FEAO33OVZM

2023-07-14 04:18 UTC, sikandeekhan commented
***@***.***

On Thu, 13 July 2023, 9:44 am Okorie150, ***@***.***> wrote:

> GABLZ2C3TINCYOWI7KCOCCJZX7EOJQ6T2BNI4TSRT3C6Q3HPRI64VTZG
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pi-apps/pi-platform-docs/pull/307#issuecomment-1633537045>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATSYISCO4J7MKAUXKYJUUQTXP54K5ANCNFSM6AAAAAAUB3INME>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-07-16 04:10 UTC, wasi4440 approved these changes

2023-07-21 21:02 UTC, joephilsopher666 approved these changes

2023-07-30 11:50 UTC, SaNaMoe requested changes

2023-07-30 11:50 UTC, SaNaMoe commented on SDK_reference.md
> +
SaNaMoe e

2023-07-30 11:53 UTC, SaNaMoe commented
GBCT2ZKP3GAITRA4XQH5C4ICCJWKF3GGPXU2Q7JFN7T3LXCN4C4ELKNV

2023-08-18 22:25 UTC, Chitel15 commented on SDK_reference.md
> +| `payments`      | Gives permission to the app to create payments on the users behalf | `createPayment` |
GBZO3OKL5CLSCSPDH76DYQUB7OPONOB3WUVN55GDC654CCA7F5P3A47S

2023-08-18 22:26 UTC, Chitel15 commented on SDK_reference.md
> +| `wallet_address` | Gives the app access to the users public wallet address | `createPayment` - App to User Payments|
GBZO3OKL5CLSCSPDH76DYQUB7OPONOB3WUVN55GDC654CCA7F5P3A47S

2023-08-18 22:28 UTC, Chitel15 commented on SDK_reference.md
> +Available scopes: `username`, `payments`, `wallet_address`.
GBZO3OKL5CLSCSPDH76DYQUB7OPONOB3WUVN55GDC654CCA7F5P3A47S

2023-08-18 22:29 UTC, Chitel15 commented
GBZO3OKL5CLSCSPDH76DYQUB7OPONOB3WUVN55GDC654CCA7F5P3A47S

2023-09-11 01:33 UTC, 1234567891011111112227 commented
Ээээ люди вы чего так много все пишите

2023-09-11 05:33 UTC, Akinte2 commented
GDCCFRHQAL4PQQRZP4G4CFSKFD63V5LPZY4CKMX3F4A6XDCOFQTJEVWB

2023-09-21 21:21 UTC, 1234567891011111112227 approved these changes

2023-09-21 21:21 UTC, 1234567891011111112227 approved these changes

2023-09-25 01:35 UTC, wasi4440 commented
CryptoGing-WalletAddress

2023-10-03 14:58 UTC, wasi4440 requested changes

2023-10-03 14:58 UTC, wasi4440 commented on SDK_reference.md
>  ### `scopes`
- [ ] # - 
```suggestion
 ### `scopes`
```

2023-10-20 04:40 UTC, Mati882023 commented on SDK_reference.md
> +Available scopes: `username`, `payments`, `wallet_address`.
-

2023-10-20 04:41 UTC, Mati882023 commented
GDIQRPPRASXROZNXKDX3P2NLSHABHSKFP3BAI5SNGXJ6WOCG3XPSA2FR

2024-01-05 16:25 UTC, ElenaCouto commented on SDK_reference.md
>  ### `scopes`
no s que hacer

2024-02-29 23:55 UTC, abboudin commented
GDIVXUHWEFW6XOPHHSJ7GFBET6WYBTZTVMI3MZNAGBDAHUAVIV6RODM3

2024-03-06 19:01 UTC, Akinte2 approved these changes

2024-03-20 04:06 UTC, Organom3000 commented
0x2ce3b2f349Dc59b148AEae85cf6bE2DD29257b16

2024-03-30 06:03 UTC, evandrofgarcia commented on SDK_reference.md
>  ### `scopes`
CryptoGing-WalletAddress

2024-03-30 06:03 UTC, evandrofgarcia commented on SDK_reference.md
SDK_reference.md

2024-04-13 14:59 UTC, evandrofgarcia approved these changes
Converter total em BRL

2024-04-26 20:35 UTC, blmitkc requested changes

2025-01-05 12:35 UTC, Andestra approved these changes

2025-01-11 21:20 UTC, Jangja55 approved these changes

2025-01-13 08:48 UTC, Andestra approved these changes

2025-01-16 14:29 UTC, Jangja55 commented
GDWR7OA4XG56T5OJUNIA2P25VMCLMXC6KCEBE55VGPWSVU6BD7BDBKIR

2025-01-16 19:00 UTC, Jangja55 commented
> เพิ่ม wallet_address ให้กับขอบเขตที่มีอยู่ และทำการเปลี่ยนแปลงการจัดรูปแบบจำนวนหนึ่งเพื่อให้ชัดเจนขึ้นว่าขอบเขตใดจำเป็นสำหรับวิธีการใด

GDWR7OA4XG56T5OJUNIA2P25VMCLMXC6KCEBE55VGPWSVU6BD7BDBKIR

2025-01-17 08:06 UTC, 301166 reviewed
Interesting!

2025-02-06 23:40 UTC, nafeef123 approved these changes

2025-02-07 22:48 UTC, nafeef123 approved these changes

2025-02-07 22:50 UTC, nafeef123 commented on SDK_reference.md
> +
- [ ]

2025-02-08 03:39 UTC, lautaseng commented
Thak

nafeef123 ***@***.***> 于 2025年2月8日周六 06:51写道：

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In SDK_reference.md
> <https://github.com/pi-apps/pi-platform-docs/pull/307#discussion_r1947291470>
> :
>
> > @@ -75,6 +76,16 @@ to be present:
>  | `uid`      | An app-local identifier for the user. This is specific to this user, and this app. It will change if the user revokes the permissions they granted to your app. | (none) |
>  | `username`   | The user's Pi username.      |   `username` |
>
> +<br />
> +
> +Here is a breakdown of scopes with no return and methods requiring them:
> +
>
>
>    - [ ]
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pi-apps/pi-platform-docs/pull/307#discussion_r1947291470>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQYLG2TOD7KH6LMDMSUOPEL2OU2GJAVCNFSM6AAAAABUUCTZDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDMMBTGAYTCMBVGA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-03-03 08:03 UTC, SS7896 commented
GABUV64U5AQ3PK7EZXPZGB6YPEGVXSLRHOGZYWPZEY62HLBD4B7363VS

2025-03-03 09:17 UTC, SS7896 reviewed
GABUV64U5AQ3PK7EZXPZGB6YPEGVXSLRHOGZYWPZEY62HLBD4B7363VS

2025-03-03 09:17 UTC, SS7896 commented on SDK_reference.md
> +| `wallet_address` | Gives the app access to the users public wallet address | `createPayment` - App to User Payments|
GABUV64U5AQ3PK7EZXPZGB6YPEGVXSLRHOGZYWPZEY62HLBD4B7363VS

2025-03-03 09:22 UTC, SS7896 requested changes

2025-03-07 02:37 UTC, trizist approved these changes
username: umairsiddiquie

2025-03-07 02:37 UTC, trizist approved these changes

2025-03-11 05:31 UTC, Nhut710579 requested changes

2025-03-11 05:31 UTC, Nhut710579 commented on SDK_reference.md
PI Network

2025-03-14 13:21 UTC, hklee93 commented
😉

2025-03-14 13:21 UTC, closed without merging