ABİT SUNGURTEKİN
pi-apps/pi-platform-docs pull request #324
Opened 2023-02-21 19:51 UTC by abitsungurtekin

abitsungurtekin

2023-02-24 03:42 UTC, ThePain813 commented
Yes this is the owner of the pain131313@gmail.com on issue#326 speaks of (my winnings) I believe someone else has taken my tokens

2023-03-06 02:09 UTC, AZIMALAVI commented
عظیم علوی

در تاریخ جمعه ۲۴ فوریهٔ ۲۰۲۳،‏ ۰۷:۱۲ ThePain813 ***@***.***>
نوشت:

> Yes this is the owner of the ***@***.*** on issue#326 speaks of
> (my winnings) I believe someone else has taken my tokens
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pi-apps/pi-platform-docs/pull/324#issuecomment-1442765592>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWXYX4FTDI62T5PIHLKGIDLWZAU2ZANCNFSM6AAAAAAVDORYJU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-03-06 08:24 UTC, closed without merging

2023-10-08 09:52 UTC, haticecan37 commented
gh pr checkout 324

2024-04-26 20:32 UTC, blmitkc approved these changes

2024-04-26 20:32 UTC, blmitkc commented on README.md
> -### Request a payment
[]()@blmitkc ```
****
```

2024-04-26 20:33 UTC, blmitkc requested changes

2024-04-26 20:33 UTC, blmitkc commented on README.md
> -### Request a payment
```
@blmitkc []()@blmitkc 
```

2024-04-26 20:37 UTC, blmitkc requested changes

2024-04-26 20:37 UTC, blmitkc commented on README.md
> -This code block is a **simplified example** to give you a sense of how it works.
Blagojmit@gmail.com **@wasi4440 ```

```**

2024-04-26 20:39 UTC, blmitkc approved these changes

2024-06-03 15:31 UTC, seck6 commented
![Snapchat-1752783396](https://github.com/pi-apps/pi-platform-docs/assets/168603861/f3d96b28-abf9-43b1-ac5b-7656e234e45b)

2024-06-03 15:31 UTC, seck6 commented
Groupe

2024-06-03 16:28 UTC, ThePain813 commented
Look to be honest with u I don't understand this stuff I stumbled on this
somehow and I'm lost and confused.can you please write your messages in
English.i need help but I get scammed every time I ask someone to help
because I don't know this crypto like I should and I think I have a lot of
funds I unaware of

On Mon, Jun 3, 2024, 8:32 AM seck6 ***@***.***> wrote:

> GABT7EMPGNCQSZM22DIYC4FNKHUVJTXITUF6Y5HNIWPU4GA7BHT4GC5G
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pi-apps/pi-platform-docs/pull/324#issuecomment-2145520874>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYU2FZDVUC5QUVCJ5WCIDK3ZFSEADAVCNFSM6AAAAAAVDORYJWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBVGUZDAOBXGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>